apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: aws-node-asg-detach
  name: aws-node-asg-detach
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - watch
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: aws-node-asg-detach
  name: aws-node-asg-detach
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-node-asg-detach
subjects:
- kind: ServiceAccount
  name: aws-node-asg-detach
  namespace: kube-system
